import type { Metadata } from 'next';
import { Rajdhani } from 'next/font/google';
import { ReactNode } from 'react';
import ThemeProvider from 'theme/ThemeProvider';
import './globals.css';

const rajdhani = Rajdhani({
    subsets: ['latin', 'devanagari'],
    variable: '--font-family-rajdhani',
    weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
    title: 'Hamaguri',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" className={`${rajdhani.variable}`}>
            <body>
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
