import type { Metadata } from 'next';
import { Rajdhani, Open_Sans } from 'next/font/google';
import { ReactNode } from 'react';
import ThemeProvider from 'theme/ThemeProvider';
import './globals.css';

const rajdhani = Rajdhani({
    subsets: ['latin'],
    variable: '--font-rajdhani',
    weight: ['400', '500', '600', '700'],
});

const openSans = Open_Sans({
    subsets: ['latin'],
    variable: '--font-opensans',
    weight: ['400'],
});

export const metadata: Metadata = {
    title: 'Hamaguri',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" className={`${rajdhani.variable} ${openSans.variable}`}>
            <body>
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
